### ISSUE TITLE
[BUG] Deployment Stuck in Final Step

### ISSUE THREAD

**Issue by yasintoy** [aws-solutions-library-samples/guidance-for-asynchronous-inference-with-stable-diffusion-on-aws#44]
**What happened**:

I'm trying to deploy the application, but after multiple attempts to run `./deploy.sh`, it always gets stuck on `cdk deploy --no-rollback --require-approval never` which is the final step.

If I re-run `cdk deploy --no-rollback --require-approval never`, its forcing me for rollback but rollback is also failing. I have to manually delete stacks

The error log is unclear to me. Could you please take a look? Is this issue related to one of the AWS service quotas, or could it be something else?

**To Reproduce**

**Attach logs**

Step 4: Start deploy... 

up to date, audited 277 packages in 1s

23 packages are looking for funding
  run npm fund for details

found 0 vulnerabilities
DEBUG Core add-on vpc-cni is at version auto
DEBUG Core add-on coredns is at version auto
DEBUG Core add-on kube-proxy is at version auto
DEBUG Core add-on kube-proxy has autoselected version v1.29.10-eksbuild.3
DEBUG Core add-on coredns has autoselected version v1.11.1-eksbuild.4
DEBUG Core add-on vpc-cni has autoselected version v1.19.0-eksbuild.1
 ⏳  Bootstrapping environment aws://559050204856/us-west-2...
Trusted accounts for deployment: (none)
Trusted accounts for lookup: (none)
Using default execution policy of 'arn:aws:iam::aws:policy/AdministratorAccess'. Pass '--cloudformation-execution-policies' to customize.
 ✅  Environment aws://559050204856/us-west-2 bootstrapped (no changes).
DEBUG Core add-on vpc-cni is at version auto
DEBUG Core add-on coredns is at version auto
DEBUG Core add-on kube-proxy is at version auto
DEBUG Core add-on kube-proxy has autoselected version v1.29.10-eksbuild.3
DEBUG Core add-on vpc-cni has autoselected version v1.19.0-eksbuild.1
DEBUG Core add-on coredns has autoselected version v1.11.1-eksbuild.4

✨  Synthesis time: 8.66s

sdoneksStack: start: Building 57159c3d4327ca77b633605cbf07135ebe55d744744e58ee8dd4b40edc569d99:559050204856-us-west-2
sdoneksStack: success: Built 57159c3d4327ca77b633605cbf07135ebe55d744744e58ee8dd4b40edc569d99:559050204856-us-west-2
sdoneksStack: start: Publishing 57159c3d4327ca77b633605cbf07135ebe55d744744e58ee8dd4b40edc569d99:559050204856-us-west-2
sdoneksStack: success: Published 57159c3d4327ca77b633605cbf07135ebe55d744744e58ee8dd4b40edc569d99:559050204856-us-west-2
sdoneksStack: deploying... [1/1]
sdoneksStack: creating CloudFormation changeset...
[██████████████████████████████████████████▋···············] (112/152)
11:09:39 PM | CREATE_FAILED        | Custom::AWSCDK-EKS-KubernetesResource | sdruntimedefaultnamespacestruct495FDEB6
Received response status [FAILED] from custom resource. Message returned: TimeoutError: {"state":"TIMEOUT","reason":"Waiter has timed out"}
at checkExceptions (/var/runtime/node_modules/@aws-sdk/node_modules/@smithy/util-waiter/dist-cjs/index.js:59:26)
at waitUntilFunctionActiveV2 (/var/runtime/node_modules/@aws-sdk/client-lambda/dist-cjs/index.js:5820:49)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async defaultInvokeFunction (/var/task/outbound.js:1:1024)
at async invokeUserFunction (/var/task/framework.js:1:2794)
at async onEvent (/var/task/framework.js:1:369)
at async Runtime.handler (/var/task/cfn-response.js:1:1826) (RequestId: c6d43e6c-6b4b-49c1-8b63-f2282b350026)

11:09:39 PM | CREATE_FAILED        | Custom::AWSCDK-EKS-KubernetesResource | sdoneksStackawsloa...ntResource3F5C0074
Received response status [FAILED] from custom resource. Message returned: TimeoutError: {"state":"TIMEOUT","reason":"Waiter has timed out"}
at checkExceptions (/var/runtime/node_modules/@aws-sdk/node_modules/@smithy/util-waiter/dist-cjs/index.js:59:26)
at waitUntilFunctionActiveV2 (/var/runtime/node_modules/@aws-sdk/client-lambda/dist-cjs/index.js:5820:49)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async defaultInvokeFunction (/var/task/outbound.js:1:1024)
at async invokeUserFunction (/var/task/framework.js:1:2794)
at async onEvent (/var/task/framework.js:1:369)
at async Runtime.handler (/var/task/cfn-response.js:1:1826) (RequestId: e5655337-ae31-4b5a-846f-041ed66dfd6f)

11:10:00 PM | CREATE_FAILED        | Custom::AWSCDK-EKS-KubernetesResource | sdoneksStackbluepr...ntResourceCCCC5486
Received response status [FAILED] from custom resource. Message returned: TimeoutError: {"state":"TIMEOUT","reason":"Waiter has timed out"}
at checkExceptions (/var/runtime/node_modules/@aws-sdk/node_modules/@smithy/util-waiter/dist-cjs/index.js:59:26)
at waitUntilFunctionActiveV2 (/var/runtime/node_modules/@aws-sdk/client-lambda/dist-cjs/index.js:5820:49)
❌  sdoneksStack failed: Error: The stack named sdoneksStack failed to deploy: CREATE_FAILED (The following resource(s) failed to create: [sdoneksStackblueprintsaddonkarpentersamanifestblueprintsaddonkarpentersaServiceAccountResourceCCCC5486, sdoneksStackawsloadbalancercontrollermanifestawsloadbalancercontrollerServiceAccountResource3F5C0074, kedanamespacestruct22C0E683, sdoneksStacks3csidriversamanifests3csidriversaServiceAccountResource690A1171, sdruntimedefaultnamespacestruct495FDEB6, sdoneksStackAwsAuthmanifest852297A8]. ): Received response status [FAILED] from custom resource. Message returned: TimeoutError: {"state":"TIMEOUT","reason":"Waiter has timed out"}
    at checkExceptions (/var/runtime/node_modules/@aws-sdk/node_modules/@smithy/util-waiter/dist-cjs/index.js:59:26)
    at waitUntilFunctionActiveV2 (/var/runtime/node_modules/@aws-sdk/client-lambda/dist-cjs/index.js:5820:49)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async defaultInvokeFunction (/var/task/outbound.js:1:1024)
    at async invokeUserFunction (/var/task/framework.js:1:2794)
    at async onEvent (/var/task/framework.js:1:369)
    at async Runtime.handler (/var/task/cfn-response.js:1:1826) (RequestId: c6d43e6c-6b4b-49c1-8b63-f2282b350026), Received response status [FAILED] from custom resource. Message returned: TimeoutError: {"state":"TIMEOUT","reason":"Waiter has timed out"}
    at checkExceptions (/var/runtime/node_modules/@aws-sdk/node_modules/@smithy/util-waiter/dist-cjs/index.js:59:26)
    at waitUntilFunctionActiveV2 (/var/runtime/node_modules/@aws-sdk/client-lambda/dist-cjs/index.js:5820:49)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async defaultInvokeFunction (/var/task/outbound.js:1:1024)
    at async invokeUserFunction (/var/task/framework.js:1:2794)
    at async onEvent (/var/task/framework.js:1:369)
    at async Runtime.handler (/var/task/cfn-response.js:1:1826) (RequestId: e5655337-ae31-4b5a-846f-041ed66dfd6f), Received response status [FAILED] from custom resource. Message returned: TimeoutError: {"state":"TIMEOUT","reason":"Waiter has timed out"}
    at checkExceptions (/var/runtime/node_modules/@aws-sdk/node_modules/@smithy/util-waiter/dist-cjs/index.js:59:26)
    at waitUntilFunctionActiveV2 (/var/runtime/node_modules/@aws-sdk/client-lambda/dist-cjs/index.js:5820:49)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async defaultInvokeFunction (/var/task/outbound.js:1:1024)
    at async invokeUserFunction (/var/task/framework.js:1:2794)
    at async onEvent (/var/task/framework.js:1:369)
    at async Runtime.handler (/var/task/cfn-response.js:1:1826) (RequestId: 35e787cf-6e4d-4ae4-a0a6-234d0d5eb027), Received response status [FAILED] from custom resource. Message returned: TimeoutError: {"state":"TIMEOUT","reason":"Waiter has timed out"}
    at checkExceptions (/var/runtime/node_modules/@aws-sdk/node_modules/@smithy/util-waiter/dist-cjs/index.js:59:26)
    at waitUntilFunctionActiveV2 (/var/runtime/node_modules/@aws-sdk/client-lambda/dist-cjs/index.js:5820:49)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async defaultInvokeFunction (/var/task/outbound.js:1:1024)
    at async invokeUserFunction (/var/task/framework.js:1:2794)
    at async onEvent (/var/task/framework.js:1:369)
    at async Runtime.handler (/var/task/cfn-response.js:1:1826) (RequestId: c918a85d-155f-4292-b8b5-613c5a4fb422), Received response status [FAILED] from custom resource. Message returned: TimeoutError: {"state":"TIMEOUT","reason":"Waiter has timed out"}
    at checkExceptions (/var/runtime/node_modules/@aws-sdk/node_modules/@smithy/util-waiter/dist-cjs/index.js:59:26)
    at waitUntilFunctionActiveV2 (/var/runtime/node_modules/@aws-sdk/client-lambda/dist-cjs/index.js:5820:49)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async defaultInvokeFunction (/var/task/outbound.js:1:1024)
    at async invokeUserFunction (/var/task/framework.js:1:2794)
    at async onEvent (/var/task/framework.js:1:369)
    at async Runtime.handler (/var/task/cfn-response.js:1:1826) (RequestId: 697236e8-c44a-4b4e-92bd-c7b9fe9ea3c5), Received response status [FAILED] from custom resource. Message returned: TimeoutError: {"state":"TIMEOUT","reason":"Waiter has timed out"}
    at checkExceptions (/var/runtime/node_modules/@aws-sdk/node_modules/@smithy/util-waiter/dist-cjs/index.js:59:26)
    at waitUntilFunctionActiveV2 (/var/runtime/node_modules/@aws-sdk/client-lambda/dist-cjs/index.js:5820:49)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async defaultInvokeFunction (/var/task/outbound.js:1:1024)
    at async invokeUserFunction (/var/task/framework.js:1:2794)
    at async onEvent (/var/task/framework.js:1:369)
    at async Runtime.handler (/var/task/cfn-response.js:1:1826) (RequestId: 8490c757-b8c7-4fbd-83fd-967bf4484761)

**What you expected to happen**:

**Anything else we need to know?**:

**Environment**:

**Comment by yubingjiaocn** [comment]
CDK uses AWS Lambda to deploy resources to EKS cluster. `Waiter has timed out` error usually means your account hits Lambda function concurrency execution limit. Could you please check your Lambda function concurrency execution limit in `Service Quota` tool? If the limit is too low (e.g. less then 50), you may try to increase the limit to 50 and try again.
